### ISSUE TITLE
The links to user-manual.adoc are wrong in asciidoc-syntax-quick-reference.adoc

### ISSUE THREAD

**Issue by youkpter** [asciidoctor/asciidoctor.org#773]
The links to user-manual in AsciiDoc Syntax Quick Reference in [asciidoctor.org][1] are wrong.
They reference to `https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/user-manual/`
instead of `https://asciidoctor.org/docs/user-manual/`

For example:

> Bold and Italic Formatting
> Quotation Marks and Apostrophes
> Subscript and Superscript
> Monospace Formatting
> Custom Styling with Attributes
> Passthrough Macros

However, It's  OK in GitHub.( I mean [here][2] )

It seems the `user` attribute is not assigned correctly in websites expect GitHub.

I'm a newbie, and sorry I don't know how to fix it.

Apologize for my poor English.

[1]: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference
[2]: https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/asciidoc-syntax-quick-reference.adoc

**Comment by mojavelinux** [comment]
Thanks for reporting! In my attempt to get the links to work on GitHub, I accidentally broke the links on the published site. It should be fixed now.

**Comment by janicesignalfx** [comment]
These links are still broken: 

<img width="681" alt="screen shot 2018-03-22 at 5 03 47 pm" src="https://user-images.githubusercontent.com/30161871/37798449-1fd1b346-2df3-11e8-8f55-ee3d53dc5490.png">

I haven't checked any others

**Comment by mojavelinux** [comment]
I believe these are now fixed.
